name: C++ CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Build Essentials
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile C++ Producer
      run: g++ main.cpp -o telemetry_sim -pthread

    - name: Verify Binary Exists
      run: ls -l telemetry_sim

    - name: Set up Python
      uses: actions/checkout@v4

    - name: Run Python Unit Tests
      run: python3 test_processor.py